ARG APP_VERSION
FROM node:20.11.1-bullseye as builder
WORKDIR /source
COPY app/package.json ./
COPY app/package-lock.json ./
COPY app/tsconfig.json ./
RUN npm install
COPY app/public ./public
COPY app/src ./src
CMD ["npm", "run", "unit-test"]
