version: '3.5'
services:
  npminstall:
    image: node:20.11.1-bullseye
    volumes:
      - "./app:/app"
    working_dir: /app
    entrypoint: ["npm", "install"]

  npmrun:
    image: node:20.11.1-bullseye
    volumes:
      - "./app:/app"
    working_dir: "/app"
    entrypoint: ["npm", "run"]
  # docker-compose -f .\services.yml run npmrun sh
  # docker-compose -f .\services.yml run npmrun build
  # docker-compose -f .\services.yml run npmrun start
  # docker-compose -f .\services.yml run npmrun test
  # docker-compose -f .\services.yml run npmrun lint
